version: '3'
services:
  zoo1:
    image: zookeeper:3.5.5
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo2:
    image: zookeeper:3.5.5
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    depends_on:
      - zoo1
  zoo3:
    image: zookeeper:3.5.5
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    depends_on:
      - zoo2
  task_db:
    image: mariadb:10.4.8-bionic
    container_name: task_db
    hostname: task_db
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=siatask"
      - "MYSQL_ROOT_HOST=%"
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  task_config:
    container_name: task_config
    build:
      context: .
      dockerfile: docker-resources/task-config/Dockerfile
    hostname: task_config
    depends_on:
      - zoo3
      - task_db
    expose:
      - 10615
      - 9009
    ports:
      - 10615:10615
      - 9109:9009
    environment:
      JAVA_OPTS: -server -Xms128m -Xmx256m -Xss256k -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:CMSIncrementalDutyCycleMin=0 -XX:CMSIncrementalDutyCycle=10 -XX:+UseParNewGC -XX:+UseCMSCompactAtFullCollection -XX:-CMSParallelRemarkEnabled -XX:CMSFullGCsBeforeCompaction=0 -XX:CMSInitiatingOccupancyFraction=70 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=. -Xdebug -Xrunjdwp:transport=dt_socket,suspend=n,server=y,address=9009
      ZOOKEEPERHOSTS: zoo1:2181
      SPRING_DATASOURCE_URL: jdbc:mysql://task_db:3306/siatask?useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_PASSWORD: root
  task_scheduler:
    container_name: task_scheduler
    build:
      context: .
      dockerfile: docker-resources/task-scheduler/Dockerfile
    hostname: task_scheduler
    depends_on:
      - zoo3
      - task_db
    expose:
      - 19011
      - 9009
    ports:
      - 19011:19011
      - 9209:9009
    environment:
      JAVA_OPTS: -server -Xms128m -Xmx256m -Xss256k -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:CMSIncrementalDutyCycleMin=0 -XX:CMSIncrementalDutyCycle=10 -XX:+UseParNewGC -XX:+UseCMSCompactAtFullCollection -XX:-CMSParallelRemarkEnabled -XX:CMSFullGCsBeforeCompaction=0 -XX:CMSInitiatingOccupancyFraction=70 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=. -Xdebug -Xrunjdwp:transport=dt_socket,suspend=n,server=y,address=9009
      ZOOKEEPERHOSTS: zoo1:2181
      SPRING_DATASOURCE_URL: jdbc:mysql://task_db:3306/siatask?useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_PASSWORD: root
  task_display:
    container_name: task_display
    build:
      context: .
      dockerfile: docker-resources/task-display/Dockerfile
    hostname: task_display
    volumes:
      - ./sia-task-config-display/dist:/app/dist
      - ./docker-resources/task-display/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      NGINX_PORT: 80
    ports:
      - 9999:80
    depends_on:
      - task_config
      - task_scheduler
  task_demo:
    build:
      context: .
      dockerfile: docker-resources/task-demo/Dockerfile
    container_name: task_demo
    hostname: task_demo
    depends_on:
      - zoo1
      - task_display
    expose:
      - 10089
    ports:
      - 10089:10089
      - 9309:9009
    environment:
      SERVER_PORT: 10089
      JAVA_OPTS: -server -Xms128m -Xmx256m -Xss256k -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:CMSIncrementalDutyCycleMin=0 -XX:CMSIncrementalDutyCycle=10 -XX:+UseParNewGC -XX:+UseCMSCompactAtFullCollection -XX:-CMSParallelRemarkEnabled -XX:CMSFullGCsBeforeCompaction=0 -XX:CMSInitiatingOccupancyFraction=70 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=. -Xdebug -Xrunjdwp:transport=dt_socket,suspend=n,server=y,address=9009
      ZOOKEEPERHOSTS: zoo1:2181
networks:
  default:
    external:
      name: sia_net