version: '3'
services:
  zoo1:
    image: zookeeper:3.5.5
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo2:
    image: zookeeper:3.5.5
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    depends_on:
      - zoo1
  zoo3:
    image: zookeeper:3.5.5
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    depends_on:
      - zoo2
  task_db:
    image: mariadb:10.4.8-bionic
    container_name: task_db
    hostname: task_db
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=siatask"
      - "MYSQL_ROOT_HOST=%"
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  default:
    external:
      name: sia_net